### ISSUE TITLE
Metric/codecheck.upy always return 0

### ISSUE THREAD

**Issue by OguzcanOzdemir** [stinb/plugins#1]
codecheck plugin is always return 0 for project, folder, file and class etc.

**Comment by kylejacksonb** [comment]
This particular plugin requires a CodeCheck configuration be setup to run in the background. When creating a CodeCheck configuration, make sure, "Run automatically in the backbround" is checked:

![image](https://github.com/stinb/plugins/assets/7936228/9de23860-6459-4aa7-9fc0-a34c394e30a0)

Afterwards, analyze your project by going to Project->Analyze All Files. After analysis, your CodeCheck configuration will automatically run. And with this plugin installed, our metrics now show up in the Metrics Browser.

![image](https://github.com/stinb/plugins/assets/7936228/d6a51602-aad9-4147-88ad-64fed5ecf8a8)

**Comment by OguzcanOzdemir** [comment]
> 

Thanks for your answer. Now, I have another question. Can you please guide me on where to configure the settings?

**Comment by kylejacksonb** [comment]
Certainly. Open the project you would like to generate a configuration for in the Understand GUI and then go to Checks->Open CodeCheck
