### ISSUE TITLE
Request for a script to calculate fan-in and fan-out for a large Python project in SciTools Understand

### ISSUE THREAD

**Issue by angiolye24** [stinb/plugins#12]
Hello! 👋

I'm working on a large Python project with SciTools Understand and am looking for a way to accurately calculate the fan-in and fan-out for specific functions across the codebase. While Understand provides basic dependency analysis, I’m encountering challenges in obtaining detailed and accurate fan-in and fan-out data for a complex Python project, which contains many interconnected modules and dynamically invoked functions.

**Comment by kylejacksonb** [comment]
For fan in/fan out metrics, we have several plugins that may help. I have a file fan metric here:
https://github.com/stinb/plugins/blob/2cd77c629c830eb76910551d879a2a98b39d9df9/Metric/file_fan.upy


I also have a set of visibility Matrix plugins here:
https://github.com/stinb/plugins/tree/2cd77c629c830eb76910551d879a2a98b39d9df9/Solutions/visibilityMatrix
