### ISSUE TITLE
Add Effective C++ to All Checks

### ISSUE THREAD

**Issue by kylejacksonb** [stinb/plugins#16]
Right now, the Effective C++ standard doesn't show up in All Checks or <None> standard. For now, let's copy the Perl checks over to All Checks and update the Python checks to be multi checks. In the future, we want to rewrite the Perl checks into Python.

**Comment by jasonbquinn** [comment]
This is now complete.

**Comment by kylejacksonb** [comment]
Thanks, Quinn
