### ISSUE TITLE
HIS Comment Density

### ISSUE THREAD

**Issue by nstander** [stinb/plugins#20]
If the following set of codecheck scripts is combined into a new python version, they should probably be updated to the new [RatioCommentsWithBeforeToCode](https://github.com/stinb/plugins/blob/main/Metric/comments.upy) metric I just added. Metrics are available from the API even if not enabled. Even if the scripts are not combined, they should be checked for correct capitalization of the metric ids because metric ids are case sensitive.

AC_HIS_01
METRIC_02
HIS_01

It's probably also worth checking scripts/hisMetricsCsv.py

**Comment by kylejacksonb** [comment]
@jordancolbeth Would rewrite HIS_01 as a Python script that uses this new metric and see if that resolves the issue with Sophie?

**Comment by jordancolbeth** [comment]
This is done with 128f0300ff96365dabee47279645cf103326b9df. I'll follow up with Sophie and have her test it.

**Comment by jordancolbeth** [comment]
hisMetricsCsv.py is fixed with c35f7abf08e46f8ae398698e091de623db028639 as well
