### ISSUE TITLE
Script error while running M15-0-3 on Linux Nightly Build

### ISSUE THREAD

**Issue by kylejacksonb** [stinb/plugins#21]
```
*** Inspection Error*** File: /jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/AUTOSAR/M15-0-3/check.upy: Inspected File: /jenkins/workspace/Testing/CodeCheck/Nightly/samples/fastgrep/fastgrep/timer.c: Error: Traceback (most recent call last):
File "/jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/AUTOSAR/M15-0-3/check.upy", line 156, in check
try_bracket.pop()
~~~~~~~~~~~~~~~^^
IndexError: pop from empty list
```

**Comment by kennethctdmn** [comment]
@kylejacksonb It seems the strict parser already addresses this error. Is this check still necessary?

**Comment by kylejacksonb** [comment]
No, go ahead and convert it to a No-op Always check.

**Comment by kylejacksonb** [comment]
@groke I still got an email from the automated system about M15-0-3 failing. Did the build machine pull before this commit?

**Comment by groke** [comment]
Yes, it pull the nightly build. I'm guessing the fix didn't actually fix as hoped

**Comment by kylejacksonb** [comment]
So the thing is, the 'fix' was deleting the UPY file and converting the check it to a Clang check. The error message is triggering on a script that shouldn't be there any more.

I did get another automated email this morning and the error with M15-0-3 is gone now. If the nightly was up to date, there is a funny delay going on.
