### ISSUE TITLE
Compiler Tag Duplicates

### ISSUE THREAD

**Issue by nstander** [stinb/plugins#25]
Remove the "Compiler" tag from duplicated checks.

Context: I want to create a smart configuration for default compiler warnings, so I created a configuration that grabs any check with the "Compiler: Default" tag. Unfortunately, many of those checks are duplicated to appear in other standards and the duplicates kept the "Compiler: Default" tag. So the smart configuration is finding 992 checks instead of the intended 403 checks. Since smart configurations are an "OR" of the listed tags, not an "AND", there's no way to remove the duplicates.

**Comment by kylejacksonb** [comment]
Fixed with 628bffaaaf8943cca3ab41b7f7d1748135eaf2a8

**Comment by nstander** [comment]
Working for me. Thanks!
