### ISSUE TITLE
Update batch_graphs.upl to not use angle brackets in file names.

### ISSUE THREAD

**Issue by kylejacksonb** [stinb/plugins#3]
Windows doesn't allow '<' and '>' characters in file names. The problem is when batch_graph calls $ent->draw() on an entity with angle brackets in the file name.

Angle brackets should be stripped from $filename in the makeFileName function.

**Comment by jordancolbeth** [comment]
This should be fixed, my Windows VM is incredibly slow though so I'm still testing.

**Comment by kylejacksonb** [comment]
Looks good.
