### ISSUE TITLE
Perl warnings in integerTypes.upl with check ID CC_PLUG_02

### ISSUE THREAD

**Issue by RobbyCBennett** [stinb/plugins#4]
Variable "%regexptests" will not stay shared at (eval 422) line 52.
Variable "%regexptests" will not stay shared at (eval 422) line 86.

**Comment by RobbyCBennett** [comment]
Replicate:
1. Install VS Code and our plugin if you haven't already
2. Open VS Code with any Understand project
3. View the output of the plugin

![image](https://github.com/user-attachments/assets/dc3d5d77-9012-449f-bf46-6fe64d53b96c)

Possibly another way to replicate:
1. Open Understand in Linux or Mac, because Understand doesn't log warnings in Windows

**Comment by RobbyCBennett** [comment]
As a side note, perhaps we should consider creating another executable for Understand called "UnderstandWithConsole.exe" which creates a console before launching a GUI. The game engine Godot does this. The official way to do this is to have Understand use WinMain as an entry point and UnderstandWithConsole use main as an entry point. It seems that Qt breaks this Windows convention.

**Comment by kylejacksonb** [comment]
> As a side note, perhaps we should consider creating another executable for Understand called "UnderstandWithConsole.exe" which creates a console before launching a GUI. The game engine Godot does this. The official way to do this is to have Understand use WinMain as an entry point and UnderstandWithConsole use main as an entry point. It seems that Qt breaks this Windows convention.

That would be the realization of a long standing dream stinb/sti#2355

**Comment by RobbyCBennett** [comment]
I don't think that's what I had in mind. That issue seems to be about an integrated terminal. Understand shouldn't log anything into that because it's for the user to compile or whatever. My idea was to have Understand log any warnings to an external console in order to work like it does on Unix.

**Comment by kylejacksonb** [comment]
It could do both

**Comment by RobbyCBennett** [comment]
Agreed. I made https://github.com/stinb/sti/issues/3386 for the external console.

**Comment by RobbyCBennett** [comment]
Fixed with https://github.com/stinb/plugins/commit/dbe13b6cd7cd55648154207922a7602779586bdc
